### ISSUE TITLE
Import a ics-file from the same server as Nextcloud is located on. 

### ISSUE THREAD

**Issue by rollanders** [stefan-muc/caldav-calendar-import#1]
I understand tghis script as a mean to import a webdav-link? I have an ics-file that I want to  import to a NC calendar. The ics is created from 5 NC-calendars combined into one calendar by a script. I can import the combined calendar ics manually but want to do it by a script as a cron-job. 

You can answer here https://help.nextcloud.com/t/add-new-calendar-from-ics-file-and-continously-update-it-with-script/57546

**Comment by stefan-muc** [comment]
> I understand tghis script as a mean to import a webdav-link?

This script imports a ``*.ics`` file into a CalDAV server as calendar events. It doesn't matter, where this file is located, as long as ``fopen()`` can access it. For my case I am fetching the file from a WebDAV URL provided by Nextcloud - but you don't have to do that too.

So seems as this script might fit your needs. I replied a bit more in detail [in the thread you linked](https://help.nextcloud.com/t/add-new-calendar-from-ics-file-and-continously-update-it-with-script/57546/18)
