### ISSUE TITLE
Missing new lines in debug mode

### ISSUE THREAD

**Issue by mossroy** [stefan-muc/caldav-calendar-import#3]
It's a very minor (cosmetic) issue

In debug mode, it displays something like : 
```

<pre>PHP version 7.3.14-1~deb10u1CalendarInfo Object
(
    [url] => /remote.php/dav/calendars/myuser/mycalendar/
    [displayname] => My calendar name
    [getctag] => http://sabre.io/ns/sync/271084
)

deleting now:

deleted 224 events, created 233 events, took 459 seconds
```
I suppose the `<pre>PHP version 7.3.14-1~deb10u1` shouldn't be there (or should be followed by a new line before "CalendarInfo Object")
And there should be a new line after `took xxx seconds`. Else the command prompt appears on the same line, right after "seconds"

**Comment by stefan-muc** [comment]
Thank you very much for pointing this out!
I fixed it in [1115fab](https://github.com/stefan-muc/caldav-calendar-import/commit/1115fab6ae4cb8abef7a469bb309f3fdce70583b) and released version 0.1.1
